---
- name: upload files to remote
  ansible.posix.synchronize:
    src: '{{ playbook_dir }}/docker/'
    dest: '/tmp/docker/'
    mode: push
    delete: yes
    recursive: yes

- name: build docker image
  community.docker.docker_image:
    name: '{{ docker.image_name }}'
    tag: '{{ docker.image_tag }}'
    build:
      path: '/tmp/docker'
    source: build
    state: present
    force_source: yes
    force_tag: yes