FROM python:3.8-slim as cron
RUN apt-get update && apt-get install -y --no-install-recommends cron tzdata
RUN apt-get update && apt-get install -y --no-install-recommends python3-virtualenv

WORKDIR /usr/src/app
ARG VIRTUAL_ENV=/opt/venv
RUN python3 -m pip install virtualenv
RUN python3 -m virtualenv --python=/usr/bin/python3 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
COPY ./requirements.txt .
RUN $VIRTUAL_ENV/bin/pip install -r requirements.txt
COPY ./*.py .
COPY ./crontab /etc/cron.d/cron-jobs
RUN chmod 0644 /etc/cron.d/cron-jobs
COPY ./cron.sh .
RUN chmod +x cron.sh
RUN mkdir -p /var/log/cron && touch /var/log/cron/cron.log

ENV TZ="Asia/Shanghai"
ENV S3_BUCKET={{ s3_bucket_name }}
ENV AWS_DEFAULT_REGION={{ vpc_region }}
ENTRYPOINT ["/bin/sh", "/usr/src/app/cron.sh"]