- name: update yum cache
  yum:
    update_cache: yes
  become: yes
  ignore_errors: yes

- name: update all packages
  yum:
    name: '*'
    state: latest
  become: yes

- name: install required packages
  yum:
    name:
      - amazon-linux-extras
    state: present
  become: yes