---
- name: install python3 and related packages
  apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - python3-wheel
      - python3-venv
    state: present
  become: yes