---
- name: install python3 for debian
  import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: install python3 for rhel
  import_tasks: redhat.yaml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: upgrade pip and related
  pip:
    name:
      - pip
      - setuptools
      - wheel
    state: latest
    virtualenv: '{{ virtualenv }}'
    virtualenv_command: /usr/bin/python3 -m venv
  become: yes

- name: import requirements
  include_vars:
    file: '{{ requirements_file }}'

- name: create python virtualenv
  pip:
    name: '{{ requirements }}'
    virtualenv: '{{ virtualenv }}'
    virtualenv_command: /usr/bin/python3 -m venv
  become: yes