---
- name: enable redhat repository
  community.general.rhsm_repository:
    name:
      - rhel-7-server-optional-rpms
    state: enabled
  become: yes
  when:
    - ansible_distribution|lower == 'redhat'

- name: install python3 and related packages
  yum:
    name:
      - python-virtualenv
      - python3
      - python3-devel
      - python3-pip
      - python3-wheel
    state: present
  become: yes